version: "3"

tasks:
  clean:
    desc: Clean up the system after all development tasks are complete.
    summary: |
      Cleanup system after development is complete.

      This command will cleanup all the unnecessary files, folder, Docker
      images/containers after development on the project is complete.

      NOTE: This is a destructive process. Please read the set of commands it
      invokes before taking an irreversible action.
    cmds:
      - docker system prune --all --force
      - rm --recursive --force /plugins

  start:
    desc: Start Neovim inside a Docker container
    summary: |
      Start Neovim inside a Docker container.

      This command will create a Docker container with Neovim running inside it.
      The container has all the necessary Neovim runtime dependencies like Python,
      Node & so on which is required by some plugins.
    cmds:
      - docker run --interactive --tty --rm \
        --volume "$(pwd)/init.lua:/root/.config/nvim/init.lua" \
        --volume "$(pwd)/lua:/root/.config/nvim/lua" \
        ghcr.io/jarmos-san/neovim-docker:main

  release:
    desc: Create a public versioned release of the project on GitHub.
    summary: |
      Create a public release on GitHub.

      This command will generate a public release on GitHub with all the necessary
      details like changelog & among other necessary information.

  build:
    desc: Build the Neovim container's Docker image locally for testing purposes.
    summary: |
      Build the Neovim Docker image locally for testing purposes.

      This command will create a local Docker image of the Neovim container. This
      should be ideally done for testing & debugging purposes only.
