name: Format the README

on: push

jobs:
  format-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the Contents of the Repository
        uses: actions/checkout@v3

      - name: Setup Prettier
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/README.md --prose-wrap always
